name: do4ds

channels:
  - conda-forge
  - nodefaults #keyword to stop it mixing channels

dependencies:
    # conda dependencies first - then pip dependencies
  - python=3.11.9
  - pip
  - pip:
    - -r requirements-dev.txt